# Dummy task

task_name: "dummy"
data: "oxfordpets"

# clip_zs -> clip zero shot, clip_lp -> clip linear probe, resnet_lp -> resnet linear probe
expts: "resnet_lp" 

#### Hyperparameters
c_clip: .05 # Regularization term for linear probe
c_resnet: .1
max_iter: 2000 # Max iters for linear probe
num_workers: 4 # Dataloader
batch_size: 100 # Dataloader

clip_model: "ViT-B/32" # ['RN50', 'RN101', 'RN50x4', 'ViT-B/32'] , options can be seen using clip.available_models()
phrases_file: "configs/phrases/default.txt" # txt file consisting of phrases to use for clip zero shot


