# Incremental class learning, evaluated on all 100 classes during test and training

num_runs: 1
data: "cifar100"
model: "alexnet"
emb: True
expt_name: "bert_icl"
output: "logs"
train_learning_type: "class" # class or task
test_learning_type: "class"

ntasks: 20
batch_size: 64
nepochs: 50
pc_valid: 0.15

workers: 4
device: "cuda"
