# Hybrid task learning, evaluated on all classes at training but at only the task specific classes at Test time
# Early stopping

num_runs: 1
data: "cifar100"
model: "alexnet"
emb: True
expt_name: "bert_icl_itl_es"
output: "logs"
train_learning_type: "class" # class or task
test_learning_type: "task"
early_stop: True

ntasks: 20
batch_size: 64
nepochs: 2
pc_valid: 0.15

workers: 4
device: "cuda"
